### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by henrilhos** [chrux/gitlab-bitbutcket-cicd#1]
Hey, I'm trying to run the script in my computer, but I get an error, I'm not so good with Python and I can't solve this error, can you help me?

This is the error:

```bash
File "export.py", line 91
    step['name'] = f'{job_key}'
                              ^
SyntaxError: invalid syntax
```

I'm using Python 2.7.16 and PIP 19.0.3

**Comment by chrux** [comment]
I just added python 2.7.16 compatibility, please pull the latest changes and run it again.
